version: "2"
x-redash-service: &redash-service
  image: redash/redash:latest
  depends_on:
    - redis
  env_file: .env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5001:5000"
    environment:
      REDASH_WEB_WORKERS: 4

  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
    networks:
      - proxynet

  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
    networks:
      - proxynet

  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
    networks:
      - proxynet

  redis:
    image: redis:5.0-alpine
    restart: always
    networks:
      - proxynet 

  nginx:
    image: redash/nginx:latest
    ports:
      - "8180:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
    networks:
      - proxynet

networks:
  proxynet:
    external: true
    name: custom_network
